# Generated by Django 4.1.7 on 2023-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
